---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: spring-resilience4j-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    role: app
